# Generated by Django 4.2.7 on 2023-11-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.TextField(blank=True)),
                ('Deadline', models.DateTimeField()),
                ('Completed', models.BooleanField(default=False)),
                ('Worker', models.TextField(blank=True)),
            ],
        ),
    ]
